{% set name = "flake8-builtins" %}
{% set version = "0.4" %}
{% set sha256 = "55e26abbf398e600069882f41166de70372302baaf49985180d1531c47b9932a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - flake8

test:
  commands:
    - "flake8 --version | grep flake8_builtins:"

about:
  home: https://github.com/gforcada/flake8-builtins
  license: GPL-2.0
  license_family: GPL2
  license_file: LICENSE
  summary: 'Check for python builtins being used as variables or parameters.'
  dev_url: https://github.com/gforcada/flake8-builtins

extra:
  recipe-maintainers:
    - dopplershift
