{% set name = "flake8-builtins" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 98833fa16139a75cd4913003492a9bd9a61c6f8ac146c3db12a2ebaf420dade3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - flake8

test:
  commands:
    - 'flake8 --version | grep flake8-builtins:'

about:
  home: https://github.com/gforcada/flake8-builtins
  license: GPL-2.0-only
  license_family: GPL2
  license_file: LICENSE
  summary: Check for python builtins being used as variables or parameters.
  dev_url: https://github.com/gforcada/flake8-builtins

extra:
  recipe-maintainers:
    - dopplershift
