{% set name = "flake8-builtins" %}
{% set version = "1.4.2" %}
{% set sha256 = "c44415fb19162ef3737056e700d5b99d48c3612a533943b4e16419a5d3de3a64" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - flake8

test:
  commands:
    - "flake8 --version | grep flake8_builtins:"

about:
  home: https://github.com/gforcada/flake8-builtins
  license: GPL-2.0
  license_family: GPL2
  license_file: LICENSE
  summary: 'Check for python builtins being used as variables or parameters.'
  dev_url: https://github.com/gforcada/flake8-builtins

extra:
  recipe-maintainers:
    - dopplershift
