travis:
  secure:
    BINSTAR_TOKEN: mq1n4fus6gHAhl+66KBVGg//IbniZ+RviorcaVlbfwlGz6rYb+bYgLzJ0O916ONDrIwiFAjT9zoIc1l124MOgfoYY30LW8TL/CJfBtHYRMaLrQ+glCYlHxDhvlFJjvIV+Nbo+zuuVGkUAo6F0nPQ9ToWa7+RS829UkQ1Sz8ZKt/yzgtLooktniSuvUOQI7E/xEXCQQDZuLOZpIaq+1Y8UZkeI+jGdYzj4BebusZvlsL7PcLsoJ8yFmk6M1g9O3qdhUngyxcmSvdb4qU1apXaRSHxoLs6ARzTGtDZY4WeugXjAuOzI0rTsna4eYifdQpKExhNTT1LS62H/XU7JwzEMuKsWa5j4J4G7J2wL/pWi/+FSTAU8EI5aOAP2/DemNlzHuwooCYCH2P1X37ELcfRiSpJfFgqrXCs/dYkrVY1St1aTh1MLtpfvahYXkZHDyRcARNqCH6dhuQUhYGZGua7LqtSs6+pHMtcDxuJR75O6u1gOY1DQVFZmY30AeJ3cENMh9/IQTmk8LnTMRt5ltpKbL7ZaucZMFFvB5YkDwQxBTy5fFSrt+ls2yZWSMHOZOXYqHuOFsxlut7Y1ZyqkDWWba63Yf6vqNliSg4vTFXM+x6VF86vgybmask2mVkZr5cwPaB+RYW7yN9wembagkisD81x9kQm+h6Nnl/SwOYJdd0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
