travis:
  secure:
    BINSTAR_TOKEN: hXa7ep7MhsPBEZ3+Hz6FMSZR/QqdAf1IujeSvJGvbRoySZNIRZYH/p0WwsjXDbyDDBv6O64vuhvRgOoQJEgBGfHCjuvGD7eOnWoGTqVekJ1FTwlDXGQH64fIALDwJpt1Hq0+RD/obcOV03Uyf0enSxogFHkLD5IMXp2t/RsxCvKj4slbJqrArAD9FcwuaALQTTmn4m/w26LkBOYuHslq/pV8vgPNvsz9dUXgsWuLa73R655ozWYbLmRbC1wNOXrq672Y/u90ewiNQf7U2z9JOESPK0J4QpB/5pRh6Efp7GrRzUGRexZQp7p2kvtUxagfc8JKg9zWJywgHGb23ob7SgnoxNtgdGo3qojVGXCK0UHUwTcFgYPBMprS0TDt3UNV16zPwNTpYjoJosrrj8XY8zGwKgUunq5VY1n1FN+/Tw2/sT74ZaGRf9khtwB2tfSOFxn0p9LKKfzroEgNzrkj3rKE1UFZ76dXQK2vQ4oO76hgkQ4/AsheNcXPeRNRDBaVz6S6mH+4TwNLUAVIW0fRMhpGvYpy46xCccmQe3fdEEE6uqTHkEgdKf2+/5SCKhaw9u6NeavirgM7IOknk8FIsI6ANZYWSyyjx6exAlWeOrR4kHXv4DXG1xDE2sKlU0p1Y/euJrXaQBw+Z7PrM0pCpfLzisJvv9ioZeXkudzyXFQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
