travis:
  secure:
    BINSTAR_TOKEN: hoxmGRxUUeXNt2R2HOvEK+nLfnWbYuDe6YwlOA+spqEqnkHBFuWNfkkYiw/U8vapFcgLQUvQwV8+iRoCcn9RZCGQNAS329GH6Pcr5AUdZrD0H1ayjQlNfU91DAu+tGVPTTrK+Yg10UF8ZXYbdMvY8O2O6tI++Bx2P/sWdqRwr7rSO1gd5YohNQMRR5OKiFWDyIdVxChCPeSaI4YH/pUzg4CBp+0etqkH2CFtzV4R/34cFF6kn4cBtaxeFE6S9mmuxZxS2nz4lYTWmlaazMloTkSGAZU31DK4qptQVcWzewS7t3ZREc+yLumvCRfJnFOnYFilrqGfQPK+TzvWw17T24GRA2QniIQaS4cRlrnXyD0j/+uhxLpiQNOeWB8g2wWFc4iB53VvOJJFs8l18hw/m2v5qpc3DssEusxXyraS/DTJyvtbpm9kYGSPZsDYfIXBJKK+dmnB4pBLFwirjrip/1r0iZInf5QzQXpiCd7i3I9d0E64On/YdVpom00jrwzSn8KdI5vrFCb7kc7T4RTiFD1B8NJ1x+RAaEneEeV1oDbhrTIDWDsHyXczddKL2uXVKqodVii2jJlxdeSfixIGQy9vVtTx3MA/gvnELg8St098nUTixfnYo1IK0yGJfOCeoaEwCHo4/pMo5pWOROEhRo+a8vlo4ZHMYlZ2c3mA6yA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
